days = {"1": {"sourdough starter weight": 0,
                  "flour weight": 100,
                  "water weight": 100,
                  "new sourdough starter weight": 200},
            "2": {"sourdough starter weight": 70,
                  "flour weight": 100,
                  "water weight": 100,
                  "new sourdough starter weight": 270},
            "3": {"sourdough starter weight": 70,
                  "flour weight": 100,
                  "water weight": 100,
                  "new sourdough starter weight": 270},
            "4": {"sourdough starter weight": 70,
                  "flour weight": 100,
                  "water weight": 100,
                  "new sourdough starter weight": 270},
            "5": {"sourdough starter weight": 70,
                  "flour weight": 100,
                  "water weight": 100,
                  "new sourdough starter weight": 270},
            "6": {"sourdough starter weight": 50,
                  "flour weight": 100,
                  "water weight": 100,
                  "new sourdough starter weight": 250},
            "7": {"sourdough starter weight": 25,
                  "flour weight": 100,
                  "water weight": 100,
                  "new sourdough starter weight": 225}
            }